from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .authentication_views import *
from .views import *

urlpatterns = [
    path('activate-code/', UserValidateAPI.as_view()),
    path('activate/<str:uid>/<str:token>/', ActivateUserByGet.as_view()),
    path('me/', UserMeRetrieveAPI.as_view()),
    path('change-password/', UserChangePasswordAPI.as_view()),
    path('get-user/', UserRetrieveAPI.as_view()),
    path('get-profile/<str:username>', UserProfileRetrieveAPI.as_view()),
    path('user-search/', UserSearchRetrieveAPI.as_view()),
    path('get-settings/', UserSettingsRetrieveAPI.as_view()),
    path('create-user/', UserCreateAPI.as_view()),
    path('login-user/', UserLoginAPI.as_view(), name="login"),
    path('delete-user/', UserAPI.as_view()),
    path('partial-update-user/', UserPartialUpdateAPI.as_view()),
    path('user-subscription/<int:pk>', UserSubscription.as_view()),
    path('user-chat-subscription/<int:pk>', UserChatSubscription.as_view()),
    path('get-card/<int:pk>', CardRetrieveAPI.as_view()),
    path('create-card/', CardCreateAPI.as_view()),
    path('create-subscription/', CreateSubscriptioAPI.as_view()),
    path('create-subscription-request/', CreateSubscriptionRequestAPI.as_view()),
    path('update-delete-card/<int:pk>', CardAPI.as_view()),
    path('partial-update-card/', CardPartialUpdateAPI.as_view()),
    path('get-donation/<int:pk>', DonationRetrieveAPI.as_view()),
    path('create-donation/', DonationCreateAPI.as_view()),
    path('get-payment/<int:pk>', PaymentRetrieveAPI.as_view()),
    path('create-payment/', PaymentCreateAPI.as_view()),
    path('validate-user/', PendingUserCreateAPI.as_view()),
    path('online-user-retrieve/', UserOnlineRetrieveAPI.as_view()),
    path('online-user-create/', UserOnlineCreateAPI.as_view()),
    path('user-cards-list/', UserCardListAPI.as_view()),
    path('user-donation-recieved/', DonationPayedUserRetrieveAPI.as_view()),
    path('user-donation-sended/', DonationPayedUserToRetrieveAPI.as_view()),
    path('user-payment-history/', PaymentUserHistoryRetrieveAPI.as_view()),
    path('pay-stats-history/', PayStatsHistoryRetrieveAPI.as_view()),
    path('referral-stats-history/', RepheralHistoryRetrieveAPI.as_view()),
    path('spend-stats-history/', SpendStatsHistoryRetrieveAPI.as_view()),
    path('credit-transfer/', CreditTransferAPI.as_view(), name='CreditTransferAPI'),
    path('block-user/', AddBlockedUserAPI.as_view(), name='BlockUser'),
    path('block-user-list/', UserBlockedListAPI.as_view(), name='BlockUserList'),
     
    path('custom-list-invite/<int:pk>', CustomUsersListInviteAPI.as_view(),
         name='CustomUsersListInviteAPI'),
    path('custom-list-delete/<int:pk>', CustomUsersListRemoveAPI.as_view(),
         name='CustomUsersListInviteAPI'),
    path('custom-list-create/', CustomUsersListCreateAPI.as_view(),
         name='CustomUsersListCreateAPI'),
    path('chat-sender-create/', ChatSenderCreateAPI.as_view(),
         name='ChatSenderCreateAPI'),
    path('custom-list-retrieve/', RetrieveUserCustomLists.as_view(),
         name='RetrieveUserCustomLists'),
    path('custom-list-retrieve-users/', RetrieveUserCustomListUsers.as_view(),
         name='RetrieveUserCustomListUsers'),
    path('custom-list-retrieve-available-users/',
         RetrieveUsersAvailableToAddToLists.as_view(), name='RetrieveUsersAvailableToAddToLists'),


    path('email-verify/', VerifyEmail.as_view(), name="email-verify"),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('request-reset-email/', RequestPasswordResetEmail.as_view(),
         name="request-reset-email"),
    path('request-restore-email/', RequestPasswordRestoreEmail.as_view(),
         name="request-restore-email"),
    path('password-reset/',
         PasswordTokenCheckAPI.as_view(), name='password-action-confirm'),
    path('password-reset-complete/', SetNewPasswordAPIView.as_view(),
         name='password-reset-complete')
]
