# Generated by Django 3.1.7 on 2021-05-09 07:54

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.FileField(upload_to='post_file', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('file', 'file'), ('music', 'music'), ('photo', 'photo'), ('video', 'video')], default='file', max_length=5, verbose_name='Тип файла')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на пост')),
                ('time_to_archive', unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True, verbose_name='Дата+время архивации')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price_to_watch', models.IntegerField(default=0, verbose_name='Цена поста')),
            ],
        ),
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Лайкнул')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к посту')),
                ('donation_amount', models.IntegerField(default=0, verbose_name='Пожертвование на пост')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.FileField(upload_to='stories', verbose_name='История')),
                ('reply_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на историю')),
                ('time_to_archive', unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True, verbose_name='Дата+время архивации')),
                ('archived', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Реакция на  историю')),
                ('like', models.BooleanField(default=False, verbose_name='Лайкнул')),
                ('watched', models.BooleanField(default=True, verbose_name='Просмотрел')),
                ('times_wathced', models.IntegerField(default=0, verbose_name='Сколько раз посмотрел')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_story', to='blog.story')),
            ],
        ),
    ]
