# Generated by Django 3.1.7 on 2021-05-09 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedstories',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_story', to=settings.AUTH_USER_MODEL, verbose_name='Создатель истории'),
        ),
        migrations.AddField(
            model_name='story',
            name='watched_story',
            field=models.ManyToManyField(through='blog.WatchedStories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель истории'),
        ),
        migrations.AddField(
            model_name='postaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_action_post', to=settings.AUTH_USER_MODEL, verbose_name='Взаимодействующий юзер'),
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(to='blog.Attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL, verbose_name='Создатель поста'),
        ),
    ]
