# Generated by Django 3.1.7 on 2021-05-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210523_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'file'), (2, 'music'), (3, 'photo'), (4, 'video')], default=1, verbose_name='Тип файла'),
        ),
    ]
