# Generated by Django 3.1.7 on 2021-06-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210523_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.Attachment', verbose_name='Вложения поста'),
        ),
    ]
