# Generated by Django 3.1.7 on 2021-06-06 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_post_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AlterField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='user_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пост в избранных'),
        ),
    ]
