# Generated by Django 3.1.7 on 2021-06-09 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20210606_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Цена покупки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bought', to='blog.post', verbose_name='Купленая публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_posts', to=settings.AUTH_USER_MODEL, verbose_name='Купивший пользователь')),
            ],
        ),
    ]
