# Generated by Django 3.1.7 on 2021-06-09 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_postbought'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbought',
            options={'verbose_name': 'Купленный пост', 'verbose_name_plural': 'Купленные посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Покупка'), (2, 'Подписка')], default=1, verbose_name='Уровень доступа'),
        ),
        migrations.AlterUniqueTogether(
            name='postbought',
            unique_together={('user', 'post')},
        ),
    ]
