# Generated by Django 3.1.7 on 2021-06-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210609_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postaction',
            unique_together=set(),
        ),
    ]
