# Generated by Django 3.1.7 on 2021-05-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to='users.user'),
            preserve_default=False,
        ),
    ]
