# Generated by Django 3.1.7 on 2021-05-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210509_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Пожертвование', 'verbose_name_plural': 'Пожертвования'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Пополнение', 'verbose_name_plural': 'Пополнения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
