# Generated by Django 3.1.7 on 2021-05-11 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210509_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AddField(
            model_name='user',
            name='my_subscribes',
            field=models.ManyToManyField(related_name='_user_my_subscribes_+', to=settings.AUTH_USER_MODEL, verbose_name='Мои подписки'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribtion_duration',
            field=models.IntegerField(default=7, verbose_name='Длина подписки в днях'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribtion_price',
            field=models.IntegerField(default=0, verbose_name='Цена подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='_user_blocked_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Заблокированные пользователи'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='Время подписки')),
                ('end_date', unixtimestampfield.fields.UnixTimeStampField(verbose_name='Время конца подписки')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Кто подписался')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписался')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='docs/', verbose_name='Документы')),
                ('verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ожидающие верификации')),
            ],
            options={
                'verbose_name': 'Пользователь на верификацию',
                'verbose_name_plural': 'Пользователи на верификацию',
            },
        ),
    ]
