# Generated by Django 3.1.7 on 2021-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210511_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Верифицирован'),
        ),
    ]
