# Generated by Django 3.1.7 on 2021-06-02 10:17

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210523_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, verbose_name='Юзернейм пользователя')),
                ('last_action', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Последнее действие пользователя',
                'verbose_name_plural': 'Последние действия пользователей',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='date_year',
            field=models.CharField(max_length=5, verbose_name='Месяц/год'),
        ),
    ]
