# Generated by Django 3.1.7 on 2021-06-06 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210602_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronline',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='_user_blocked_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Заблокированные пользователи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_subscribes',
            field=models.ManyToManyField(blank=True, related_name='_user_my_subscribes_+', to=settings.AUTH_USER_MODEL, verbose_name='Мои подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='repheral_users',
            field=models.ManyToManyField(blank=True, related_name='_user_repheral_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Реферальные пользователи'),
        ),
        migrations.AlterField(
            model_name='useronline',
            name='user',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Юзернейм пользователя'),
        ),
    ]
