# Generated by Django 3.1.7 on 2021-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210606_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_price',
            field=models.IntegerField(default=0, verbose_name='Цена сообщений'),
        ),
    ]
