# Generated by Django 3.1.7 on 2021-10-23 14:49

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_message_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='Время пополнения'),
        ),
    ]
