# Generated by Django 3.1.7 on 2021-10-29 00:10

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211023_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=unixtimestampfield.fields.UnixTimeStampField(verbose_name='Время пополнения'),
        ),
    ]
