# Generated by Django 3.1.7 on 2021-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Номер карты'),
        ),
    ]
