# Generated by Django 3.1.7 on 2021-05-09 07:54

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True, verbose_name='Send datetime')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
        ),
    ]
