# Generated by Django 3.1.7 on 2021-10-29 00:10

import core.utils.func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210609_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.func.room_logo, verbose_name='Заставка комнаты'),
        ),
    ]
